version: '3'

services:
    app:
        container_name: gift_list_app
        restart: unless-stopped
        build:
            context: ../
            dockerfile: docker/app/dev.Dockerfile
        environment:
            - APP_ENV=dev
            - LANG=fr_FR.UTF-8
            - PORT=3000
        ports:
            - 3000:3000
        volumes:
            - '../app:/home/app'
            - './app/.env:/home/app/.env'
            - '/home/app/node_modules'
        networks:
            - app-network

    gift_list_db:
        image: postgres
        container_name: gift_list_db
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_PORT=5432
        volumes:
            - db_gift_list_data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    db_gift_list_data:

networks:
    app-network:
        driver: bridge
